using System.ComponentModel.DataAnnotations;

namespace KinoPrototype;

//1 user can have many JoinEvents
public class Host
{
    [Key] public int Id { get; set; }
    public string Username { get; set; }
}

//1 JoinEvent can have many Participants
public class Participant
{
    [Key] public int Id { get; set; }
    public string Nickname { get; set; }
}

//1 JoinEvent hosted by 1 user can have many Showtimes
public class JoinEvent
{
    [Key] public int Id { get; set; } //own key.
    public Host Host { get; set; } //1 user can have many JoinEvents
    public List<Participant> Participants { get; set; } //1 JoinEvent can have many Participants
    
    public string Title { get; set; } //"min seje fødselsdag"
    public string Description { get; set; } //"vi mødes ved dør 1"
    public DateTime Deadline { get; set; } // "event skal svares på inden 01-01-2021"
    public List<Showtimes> Showtimes { get; set; }
    // Timeframe is autogenerated: 01.01.2020 - 01.10.2020  (showtime.Min(e -> e.showtime) - showtime.Max(e -> e.showtime))
    // Location is autogenerated 
}

public class Showtimes
{
    [Key] public int Id { get; set; } // kinos own key. Ex 1534940
    public string Label { get; set; } // content.label: "poor things"
    
    
}